### ISSUE TITLE
UTM zone behaviour with stray comma

### ISSUE THREAD

**Issue by mwtoews** [OSGeo/PROJ#2671]
This issue was found [out in the open](https://gis.stackexchange.com/q/393748/).

Take a proj string with a stray comma in `+zone=23K,`, and check an example point, then run proj from versions 4.9.3, 7.1.1 and 8.0.0 releases:
```bash
$ prj_str="+proj=utm +zone=23K, +south +ellps=WGS84 +datum=WGS84 +units=m +no_defs"
$ lonlat_str="-47.059235202 -22.818009494"
$ echo $lonlat_str | ./proj-4.9.3-cmake/bin/proj $prj_str 
288652.54	7475153.00
$ echo $lonlat_str | ./proj-7.1.1-cmake/bin/proj $prj_str 
288652.54	7475153.00
$ echo $lonlat_str | ./proj-8.0.0-cmake/bin/proj $prj_str 
288652.54	-2524847.00
```
Note the wrong northing from PROJ 8.0.0.

Using pyproj to investigate shows that `+zone=23K,` is somehow translated to UTM zone 23N, which explains the negative northing:
```ipython
In [1]: from pyproj import CRS

In [2]: crs = CRS.from_proj4("+proj=utm +zone=23K, +south +ellps=WGS84 +datum=WGS84 +units=m +no_defs")

In [3]: crs
Out[3]: 
<Projected CRS: +proj=utm +zone=23K, +south +ellps=WGS84 +datum=WG ...>
Name: unknown
Axis Info [cartesian]:
- E[east]: Easting (metre)
- N[north]: Northing (metre)
Area of Use:
- undefined
Coordinate Operation:
- name: UTM zone 23N
- method: Transverse Mercator
Datum: World Geodetic System 1984
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich
```
Should PROJ use the prior behaviour (ignoring the stray comma), or throw an error?

As for the latitude band letter `K`, it seems that this is ignored. It is documented to be a value between 1-60. The issue above is possibly that the comma somehow prevented `+south` from being parsed.

**Comment by rouault** [comment]
I had a hard time understand what happens here. The reason of the change of behaviour is that in PROJ 8 there were simplification in how proj strings are parsed (several ways could be taken before), and now this comes to the pj_shrink() functions that has a  mechanism to make ',' "greedy". So the " +zone=23K, +south" part becomes parsed as a parameter "zone=23K,south", thus appending the 'south' parameter as a value of 'zone' .
I can see this behaviour helps more human friendly notations like that example in test/gie/4D-API_cs2cs-style.gie
```
operation proj=latlong ellps=intl \
          towgs84 =  -081.07030, -089.36030, -115.75260, \
                      000.48488, 000.02436, 000.41321, -0.540645
```
The best behavour here would be to error out when the zone value is not an integer value.

**Comment by kbevers** [comment]
> The best behavour here would be to error out when the zone value is not an integer value.

Agreed. I was surprised that it worked in the first place.

**Comment by mwtoews** [comment]
Thanks for the fix @rouault ! Raising an error is the right thing here. An earlier [duplicate question](https://gis.stackexchange.com/q/370838/) shows there's some unexpected temptation to use a comma before `+south`.

**Comment by jorisvandenbossche** [comment]
In GeoPandas, we had a test using `"+proj=utm +zone=30N +type=crs"`, which now started to raise an error. But so this only happened to work "by accident" before? (because the north zone is the default, eg using `+zone=30S` would still give the north zone)

**Comment by rouault** [comment]
> But so this only happened to work "by accident" before? (because the north zone is the default, eg using `+zone=30S` would still give the north zone)

yes. That said I guess supporting 30N / 30S syntax could be a reasonable enhancement

**Comment by kbevers** [comment]
> That said I guess supporting 30N / 30S syntax could be a reasonable enhancement

Not so sure about that. They may be confused for latitude bands which sometimes used: https://en.wikipedia.org/wiki/Universal_Transverse_Mercator_coordinate_system#Latitude_bands

**Comment by jorisvandenbossche** [comment]
Thanks for the quick response. We fixed our tests then ;)

**Comment by mwtoews** [comment]
Using the latitude band notation, zone 30N shown [here](https://en.wikipedia.org/wiki/Universal_Transverse_Mercator_coordinate_system#/media/File:LA2-Africa-UTM-zones.png) is in Côte d'Ivoire and Ghana, which are in the southern hemisphere. So raising an error is still the correct thing to do when expecting only an integer zone.

**Comment by busstoptaktik** [comment]
> Côte d'Ivoire and Ghana, which are in the southern hemisphere

@mwtoews Ghana and  Côte d'Ivoire are in the northern hemisphere (Ghana's capital, Accra, on its southern coast is at 5 degrees N)

**Comment by mwtoews** [comment]
facepalm :facepalm:
A better example is zone 30S ([here](https://en.wikipedia.org/wiki/Universal_Transverse_Mercator_coordinate_system#/media/File:LA2-Europe-UTM-zones.png)), which is not in the southern hemisphere.
